Repository next-frame-lab/api-server, pull requests merged in 2025-07, with the labels that each got.

#6 #5 refactor(domain): 도메인 행위 명확화 및 UUID/금액 타입을 값 객체로 모델링 개선
  src/main/java/wisoft/nextframe/common/Money.java
  src/main/java/wisoft/nextframe/payment/Payment.java
  src/main/java/wisoft/nextframe/payment/refund/Refund.java
  src/main/java/wisoft/nextframe/payment/refund/RefundId.java
  src/main/java/wisoft/nextframe/payment/refund/RefundPolicyStatus.java
  src/main/java/wisoft/nextframe/payment/refund/RefundService.java
  src/main/java/wisoft/nextframe/payment/refund/RefundStatus.java
  src/main/java/wisoft/nextframe/refund/Refund.java
  src/main/java/wisoft/nextframe/refund/RefundPolicyStatus.java
  src/main/java/wisoft/nextframe/refund/RefundStatus.java
  src/main/java/wisoft/nextframe/reservation/ReservationId.java
  src/main/java/wisoft/nextframe/ticket/Ticket.java
  src/main/java/wisoft/nextframe/ticket/TicketId.java
  src/main/java/wisoft/nextframe/ticket/TicketService.java
  src/test/java/wisoft/nextframe/common/MoneyTest.java
  src/test/java/wisoft/nextframe/payment/PaymentTest.java
  src/test/java/wisoft/nextframe/payment/TestPaymentFactory.java
  src/test/java/wisoft/nextframe/payment/refund/RefundPolicyStatusTest.java
  src/test/java/wisoft/nextframe/payment/refund/RefundServiceTest.java
  src/test/java/wisoft/nextframe/payment/refund/RefundTest.java
  src/test/java/wisoft/nextframe/payment/refund/TestRefundFactory.java
  src/test/java/wisoft/nextframe/refund/RefundPolicyStatusTest.java
  src/test/java/wisoft/nextframe/refund/RefundServiceTest.java
  src/test/java/wisoft/nextframe/refund/TestRefundFactory.java
  src/test/java/wisoft/nextframe/ticket/TicketServiceTest.java
  src/test/java/wisoft/nextframe/ticket/TicketTest.java
Labels: status: done, type: improvement

#8 #7 refactor domain exceptions
  src/main/java/wisoft/nextframe/common/Money.java
  src/main/java/wisoft/nextframe/common/exception/InvalidAmountException.java
  src/main/java/wisoft/nextframe/global/ErrorResponse.java
  src/main/java/wisoft/nextframe/global/GlobalExceptionHandler.java
  src/main/java/wisoft/nextframe/payment/Payment.java
  src/main/java/wisoft/nextframe/payment/PaymentIssuer.java
  src/main/java/wisoft/nextframe/payment/exception/InvalidPaymentStatusException.java
  src/main/java/wisoft/nextframe/payment/exception/MissingReservationException.java
  src/main/java/wisoft/nextframe/payment/exception/PaymentAlreadySucceededException.java
  src/main/java/wisoft/nextframe/payment/exception/PaymentException.java
  src/main/java/wisoft/nextframe/payment/exception/RefundAlreadyExistsException.java
  src/main/java/wisoft/nextframe/payment/exception/TooLargeAmountException.java
  src/main/java/wisoft/nextframe/payment/refund/Refund.java
  src/main/java/wisoft/nextframe/payment/refund/RefundService.java
  src/main/java/wisoft/nextframe/payment/refund/exception/InvalidRefundStatusException.java
  src/main/java/wisoft/nextframe/payment/refund/exception/NotRefundableException.java
  src/main/java/wisoft/nextframe/payment/refund/exception/RefundException.java
  src/main/java/wisoft/nextframe/ticket/TicketService.java
  src/main/java/wisoft/nextframe/ticket/exception/CannotIssueTicketWithoutPaymentException.java
  src/test/java/wisoft/nextframe/common/MoneyTest.java
  src/test/java/wisoft/nextframe/payment/PaymentTest.java
  src/test/java/wisoft/nextframe/ticket/TicketServiceTest.java
Labels: status: review, type: refactor

#10 docs: Swagger API 명세 파일 작성
  src/main/resources/openapi/openapi-v1.yaml
Labels: status: review, type: documentation
