Repository next-frame-lab/api-server, pull requests merged in 2025-09, with the labels that each got.

#58 #55 fix(test): TicketService 테스트 로직 saveAndFlush로 수정 및 불필요 stubbing 제거
  schedule-reservation-ticketing/src/test/java/wisoft/nextframe/schedulereservationticketing/service/ticketing/TicketServiceTest.java
Labels: status: done, type: bug

#62 fix payment 서버에서 schedule-reservation-ticketing 서버 분리
  payment/src/main/java/wisoft/nextframe/payment/PaymentApplication.java
Labels: status: done, type: bug

#76 #71 refactor(reservation): 토큰 기반으로 예약자 정보 처리 변경
  schedule-reservation-ticketing/src/main/java/wisoft/nextframe/schedulereservationticketing/common/filter/JwtAuthenticationFilter.java
  schedule-reservation-ticketing/src/main/java/wisoft/nextframe/schedulereservationticketing/controller/reservation/ReservationController.java
  schedule-reservation-ticketing/src/main/java/wisoft/nextframe/schedulereservationticketing/dto/reservation/request/ReservationRequest.java
  schedule-reservation-ticketing/src/main/java/wisoft/nextframe/schedulereservationticketing/service/reservation/ReservationDataProvider.java
  schedule-reservation-ticketing/src/main/java/wisoft/nextframe/schedulereservationticketing/service/reservation/ReservationService.java
Labels: status: review, type: feature

#82 #77 chore: 모노레포 CD 워크플로우 구성
  .github/workflows/cd.yml
Labels: status: review, type: chore

#83 #81 fix(ticketing): TicketingAdaptor에 사용할 base URL Port 수정
  payment/src/main/java/wisoft/nextframe/payment/infra/payment/adaptor/TicketingAdaptor.java
Labels: status: done

#87 #86 improvement(workflow): CI/CD 워크플로우 최적화
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: status: review, type: improvement
